version: '3.8'
services:
  moodle:
    build:
      context: .
      target: development
    container_name: moodle-dev
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - moodledata:/var/www/moodledata
    environment:
      - MOODLE_DOCKER_DBTYPE=mysqli
      - MOODLE_DOCKER_DBHOST=db
      - MOODLE_DOCKER_DBNAME=moodle
      - MOODLE_DOCKER_DBUSER=moodle
      - MOODLE_DOCKER_DBPASS=moodle
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: moodle-db
    restart: always
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
  moodledata:
